services:
  go-playground:
    container_name: go-playground
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 8080:8080
      - 2345:2345 # for delve headless debugging server
    entrypoint: ["make", "dev"] # ["make", "run"]
